<a href="https://colab.research.google.com/github/adihebbalae/randos/blob/main/Lin_Alg_Quiz15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import itertools
# import numpy as np

# def generate_3x3_matrices():

#     all_combinations = list(itertools.product([0, 1], repeat=9))
#     matrices = [np.array(combination).reshape(3, 3) for combination in all_combinations]

#     return matrices

# if __name__ == "__main__":
#     # Generate the matrices
#     matrices = generate_3x3_matrices()

#     for i, matrix in enumerate(matrices[:5]):
#         print(f"Matrix {i+1}:\n{matrix}\n")

#     print(f"Total matrices generated: {len(matrices)}")


Matrix 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Matrix 2:
[[0 0 0]
 [0 0 0]
 [0 0 1]]

Matrix 3:
[[0 0 0]
 [0 0 0]
 [0 1 0]]

Matrix 4:
[[0 0 0]
 [0 0 0]
 [0 1 1]]

Matrix 5:
[[0 0 0]
 [0 0 0]
 [1 0 0]]

Total matrices generated: 512


In [ ]:
import itertools
import numpy as np

def generate_3x3_matrices():
    all_combinations = list(itertools.product([0, 1], repeat=9))
    matrices = [np.array(combination).reshape(3, 3) for combination in all_combinations]
    return matrices

def convert_to_9x1(matrix):
    return matrix.T.flatten()

def calculate_ones_count(matrix, M):
    n = convert_to_9x1(matrix)
    return int(n.T @ M @ n)


if __name__ == "__main__":
    matrices = generate_3x3_matrices()
    M = np.eye(9)

    results = []
    for matrix in matrices:
        n = convert_to_9x1(matrix)
        ones_count = int(n.T @ M @ n)
        results.append((matrix, ones_count))

    with open("output_matrices.txt", "w") as f:
        for i, (matrix, ones_count) in enumerate(results):
            f.write(f"Matrix {i+1}:\n{matrix}\nNumber of 1s: {ones_count}\n\n")
    print("All matrices saved to 'output_matrices.txt'.")



All matrices saved to 'output_matrices.txt'.


All matrices saved to 'output_matrices.txt'.
